---
title: Teguh Setiawan's Website
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
baseurl: ''
url: https://teguh-setiawan.com
github_username: teguh-elektro
instagram_username: midori.board
youtube_username: "@teguhsetiawan8910"
disqus:
  shortname: teguh-elektro
google_analytics: G-FZNZ964PT3
theme: minima
plugins:
- jekyll-feed
- jekyll-paginate
include:
- _uploads
- ads.txt
paginate: 4
